In [1]:
import pandas as p
import numpy as n

In [4]:
data=p.read_csv('data/OPD-Under-5-years-2012.csv')

In [5]:
data

,Region,Malaria,Acute Respiratory Infection,Diarrhoeal Disease,Intestinal Worms,Pneumonia,Eye Infections,Ear Infections,Skin Infections,Bronchial Asthma,...,HIV/AIDS,Non-Infectious Skin Disease,Vitamin A Def Xerophthalmia,Non-Infectious Eye Dis (ukitoa Vitamin A deficiency),Joint Disorders,Dental Caries,Other oral disorders,Ill Defined Symptoms (No diagnosis),Others,Total
0,Arusha,88100,140656,41686,26271,93626,22681,11382,13650,1182,...,625,2321,8,690,1,886,1290,8585,15519,507637
1,Dar es Salaam,385645,162618,108668,109747,114209,37722,27380,65677,9573,...,1064,12867,17,107,11,27120,9883,23002,6101,1247128
2,Dodoma,96628,123478,44150,16514,34436,21125,7326,18729,3503,...,132,3220,45,239,52,270,405,9641,10429,419274
3,Iringa,65197,105096,36377,16986,41557,11217,7319,21946,1995,...,779,268,73,287,27,1550,839,8880,14211,355088
4,Kagera,220091,133368,40876,32414,53750,11155,5857,12271,876,...,246,2123,3,311,84,188,63,6811,19356,574222
5,Kigoma,235244,110309,37748,31093,29825,12507,7229,12437,600,...,93,2887,10,1217,44,1041,633,12316,6720,545378
6,Kilimanjaro,206942,169335,37295,91748,119701,22478,18361,27234,7880,...,1264,3251,0,214,15,220,120,9497,8402,757625
7,Lindi,182107,103472,26335,9168,25590,14573,4706,10875,1823,...,105,3973,259,61,26,291,187,9975,11711,428776
8,Mara,337855,119292,143524,49823,120829,14802,9615,14920,2856,...,153,3759,38,109,16,35,1417,18161,32070,1038351
9,Manyara,100352,82676,44367,14480,58381,9972,5177,12467,533,...,786,1561,22,120,160,540,235,5260,10903,364972
10,Mbeya,191570,144125,80435,20048,66033,13203,9476,26854,1678,...,784,1143,67,88,109,578,350,9237,23877,628782
11,Morogoro,343580,127672,42888,33193,74177,15492,9639,32324,2476,...,453,2769,1478,482,3461,829,1562,7971,21887,755658
12,Mtwara,193526,61493,21698,6733,31277,15192,4214,12521,1989,...,415,1310,43,38,14,123,933,6456,10357,385657
13,Mwanza,367850,201567,89949,51561,86162,26111,14911,29482,1668,...,502,12726,14,1230,36,852,546,20606,60833,1073680
14,Total,164054,38326,19137,10751,31481,9736,3723,14104,3115,...,97,2869,7,621,11,952,101,1252,6358,360436
15,Rukwa,151923,115390,230553,21342,41228,19844,7638,18686,1166,...,931,3696,0,99,33,859,53,4856,16947,677003
16,Ruvuma,224364,95236,26144,14144,58348,14916,19652,17310,2189,...,200,2595,0,88,37,259,354,5884,8076,513363
17,Singida,159224,130384,48248,16935,39662,15767,7301,9364,645,...,464,350,224,36,4,169,2548,7673,19282,481794
18,Shinyanga,415972,172045,81310,33417,65534,14036,10818,20233,1898,...,1441,5223,39,88,10,125,128,7667,12435,916946
19,Tabora,278184,69464,42911,18874,32533,11400,3692,15339,1238,...,0,1672,0,0,2,19,111,5822,19252,524208
20,Tanga,453194,219216,67456,45473,121480,26090,20284,16507,3911,...,83,14972,0,58,147,5668,23003,91396,249414,1455493

In [6]:
data.shape

(21, 32)

In [9]:
data.describe()

,Malaria,Acute Respiratory Infection,Diarrhoeal Disease,Intestinal Worms,Pneumonia,Eye Infections,Ear Infections,Skin Infections,Bronchial Asthma,Cardiovascular Diseases,...,HIV/AIDS,Non-Infectious Skin Disease,Vitamin A Def Xerophthalmia,Non-Infectious Eye Dis (ukitoa Vitamin A deficiency),Joint Disorders,Dental Caries,Other oral disorders,Ill Defined Symptoms (No diagnosis),Others,Total
count,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.00000,21.000000,21.000000,...,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,2.100000e+01
mean,231504.857143,125010.380952,62464.523810,31938.809524,63800.904762,17143.761905,10271.428571,20139.52381,2514.000000,377.476190,...,505.571429,4074.047619,111.761905,294.428571,204.761905,2027.333333,2131.476190,13378.476190,27816.190476,6.672129e+05
std,113484.127205,44474.603485,49514.976403,26354.653951,33206.943733,6887.070668,6374.155454,12252.18753,2279.675437,660.464126,...,421.743710,4148.610761,320.724478,362.642878,747.496816,5872.105383,5228.977736,18629.138881,52186.909672,3.121315e+05
min,65197.000000,38326.000000,19137.000000,6733.000000,25590.000000,9736.000000,3692.000000,9364.00000,533.000000,36.000000,...,0.000000,268.000000,0.000000,0.000000,1.000000,19.000000,53.000000,1252.000000,6101.000000,3.550880e+05
25%,159224.000000,103472.000000,37295.000000,16514.000000,34436.000000,12507.000000,5857.000000,12521.00000,1182.000000,102.000000,...,132.000000,1672.000000,3.000000,88.000000,11.000000,188.000000,128.000000,6456.000000,10357.000000,4.287760e+05
50%,206942.000000,123478.000000,42911.000000,21342.000000,58348.000000,14916.000000,7638.000000,16507.00000,1898.000000,166.000000,...,453.000000,2869.000000,17.000000,109.000000,27.000000,540.000000,405.000000,8585.000000,14211.000000,5.453780e+05
75%,337855.000000,144125.000000,80435.000000,33417.000000,86162.000000,21125.000000,11382.000000,21946.00000,2856.000000,249.000000,...,784.000000,3759.000000,45.000000,311.000000,52.000000,886.000000,1290.000000,9975.000000,19356.000000,7.576250e+05
max,453194.000000,219216.000000,230553.000000,109747.000000,121480.000000,37722.000000,27380.000000,65677.00000,9573.000000,2996.000000,...,1441.000000,14972.000000,1478.000000,1230.000000,3461.000000,27120.000000,23003.000000,91396.000000,249414.000000,1.455493e+06

In [10]:
for column in data.columns:
    print(column)

Region
Malaria
Acute Respiratory Infection
Diarrhoeal Disease
Intestinal Worms
Pneumonia
Eye Infections
Ear Infections
Skin Infections
Bronchial Asthma
Cardiovascular Diseases
Sexually Transmitted diseases
Urinary Tract Infections
Anaemia
Schistosomiasis
Protein Energy Malnutrition
Other Nutritional Disorders
Epilepsy
Burns
Poisoning
Minor surgical Conditions
Tuberculosis
HIV/AIDS
Non-Infectious Skin Disease
Vitamin A Def Xerophthalmia
Non-Infectious Eye Dis (ukitoa Vitamin  A deficiency)
Joint Disorders
Dental Caries
Other oral disorders
Ill Defined Symptoms (No diagnosis)
Others
Total

In [11]:
X = data.drop('Region',axis = 1)
y = data.Region

In [16]:
X=p.get_dummies(X)

In [17]:
y

0            Arusha
1     Dar es Salaam
2            Dodoma
3            Iringa
4            Kagera
5            Kigoma
6       Kilimanjaro
7             Lindi
8              Mara
9           Manyara
10            Mbeya
11         Morogoro
12           Mtwara
13          Mwanza
14            Total
15            Rukwa
16           Ruvuma
17          Singida
18        Shinyanga
19          Tabora
20           Tanga
Name: Region, dtype: object

,Region,Malaria,Acute Respiratory Infection,Diarrhoeal Disease,Intestinal Worms,Pneumonia,Eye Infections,Ear Infections,Skin Infections,Bronchial Asthma,...,HIV/AIDS,Non-Infectious Skin Disease,Vitamin A Def Xerophthalmia,Non-Infectious Eye Dis (ukitoa Vitamin A deficiency),Joint Disorders,Dental Caries,Other oral disorders,Ill Defined Symptoms (No diagnosis),Others,Total
0,Arusha,88100,140656,41686,26271,93626,22681,11382,13650,1182,...,625,2321,8,690,1,886,1290,8585,15519,507637
1,Dar es Salaam,385645,162618,108668,109747,114209,37722,27380,65677,9573,...,1064,12867,17,107,11,27120,9883,23002,6101,1247128
2,Dodoma,96628,123478,44150,16514,34436,21125,7326,18729,3503,...,132,3220,45,239,52,270,405,9641,10429,419274
3,Iringa,65197,105096,36377,16986,41557,11217,7319,21946,1995,...,779,268,73,287,27,1550,839,8880,14211,355088
4,Kagera,220091,133368,40876,32414,53750,11155,5857,12271,876,...,246,2123,3,311,84,188,63,6811,19356,574222
5,Kigoma,235244,110309,37748,31093,29825,12507,7229,12437,600,...,93,2887,10,1217,44,1041,633,12316,6720,545378
6,Kilimanjaro,206942,169335,37295,91748,119701,22478,18361,27234,7880,...,1264,3251,0,214,15,220,120,9497,8402,757625
7,Lindi,182107,103472,26335,9168,25590,14573,4706,10875,1823,...,105,3973,259,61,26,291,187,9975,11711,428776
8,Mara,337855,119292,143524,49823,120829,14802,9615,14920,2856,...,153,3759,38,109,16,35,1417,18161,32070,1038351
9,Manyara,100352,82676,44367,14480,58381,9972,5177,12467,533,...,786,1561,22,120,160,540,235,5260,10903,364972
10,Mbeya,191570,144125,80435,20048,66033,13203,9476,26854,1678,...,784,1143,67,88,109,578,350,9237,23877,628782
11,Morogoro,343580,127672,42888,33193,74177,15492,9639,32324,2476,...,453,2769,1478,482,3461,829,1562,7971,21887,755658
12,Mtwara,193526,61493,21698,6733,31277,15192,4214,12521,1989,...,415,1310,43,38,14,123,933,6456,10357,385657
13,Mwanza,367850,201567,89949,51561,86162,26111,14911,29482,1668,...,502,12726,14,1230,36,852,546,20606,60833,1073680
14,Total,164054,38326,19137,10751,31481,9736,3723,14104,3115,...,97,2869,7,621,11,952,101,1252,6358,360436
15,Rukwa,151923,115390,230553,21342,41228,19844,7638,18686,1166,...,931,3696,0,99,33,859,53,4856,16947,677003
16,Ruvuma,224364,95236,26144,14144,58348,14916,19652,17310,2189,...,200,2595,0,88,37,259,354,5884,8076,513363
17,Singida,159224,130384,48248,16935,39662,15767,7301,9364,645,...,464,350,224,36,4,169,2548,7673,19282,481794
18,Shinyanga,415972,172045,81310,33417,65534,14036,10818,20233,1898,...,1441,5223,39,88,10,125,128,7667,12435,916946
19,Tabora,278184,69464,42911,18874,32533,11400,3692,15339,1238,...,0,1672,0,0,2,19,111,5822,19252,524208
20,Tanga,453194,219216,67456,45473,121480,26090,20284,16507,3911,...,83,14972,0,58,147,5668,23003,91396,249414,1455493

In [20]:
df=p.DataFrame(data)
df

,Region,Malaria,Acute Respiratory Infection,Diarrhoeal Disease,Intestinal Worms,Pneumonia,Eye Infections,Ear Infections,Skin Infections,Bronchial Asthma,...,HIV/AIDS,Non-Infectious Skin Disease,Vitamin A Def Xerophthalmia,Non-Infectious Eye Dis (ukitoa Vitamin A deficiency),Joint Disorders,Dental Caries,Other oral disorders,Ill Defined Symptoms (No diagnosis),Others,Total
0,Arusha,88100,140656,41686,26271,93626,22681,11382,13650,1182,...,625,2321,8,690,1,886,1290,8585,15519,507637
1,Dar es Salaam,385645,162618,108668,109747,114209,37722,27380,65677,9573,...,1064,12867,17,107,11,27120,9883,23002,6101,1247128
2,Dodoma,96628,123478,44150,16514,34436,21125,7326,18729,3503,...,132,3220,45,239,52,270,405,9641,10429,419274
3,Iringa,65197,105096,36377,16986,41557,11217,7319,21946,1995,...,779,268,73,287,27,1550,839,8880,14211,355088
4,Kagera,220091,133368,40876,32414,53750,11155,5857,12271,876,...,246,2123,3,311,84,188,63,6811,19356,574222
5,Kigoma,235244,110309,37748,31093,29825,12507,7229,12437,600,...,93,2887,10,1217,44,1041,633,12316,6720,545378
6,Kilimanjaro,206942,169335,37295,91748,119701,22478,18361,27234,7880,...,1264,3251,0,214,15,220,120,9497,8402,757625
7,Lindi,182107,103472,26335,9168,25590,14573,4706,10875,1823,...,105,3973,259,61,26,291,187,9975,11711,428776
8,Mara,337855,119292,143524,49823,120829,14802,9615,14920,2856,...,153,3759,38,109,16,35,1417,18161,32070,1038351
9,Manyara,100352,82676,44367,14480,58381,9972,5177,12467,533,...,786,1561,22,120,160,540,235,5260,10903,364972
10,Mbeya,191570,144125,80435,20048,66033,13203,9476,26854,1678,...,784,1143,67,88,109,578,350,9237,23877,628782
11,Morogoro,343580,127672,42888,33193,74177,15492,9639,32324,2476,...,453,2769,1478,482,3461,829,1562,7971,21887,755658
12,Mtwara,193526,61493,21698,6733,31277,15192,4214,12521,1989,...,415,1310,43,38,14,123,933,6456,10357,385657
13,Mwanza,367850,201567,89949,51561,86162,26111,14911,29482,1668,...,502,12726,14,1230,36,852,546,20606,60833,1073680
14,Total,164054,38326,19137,10751,31481,9736,3723,14104,3115,...,97,2869,7,621,11,952,101,1252,6358,360436
15,Rukwa,151923,115390,230553,21342,41228,19844,7638,18686,1166,...,931,3696,0,99,33,859,53,4856,16947,677003
16,Ruvuma,224364,95236,26144,14144,58348,14916,19652,17310,2189,...,200,2595,0,88,37,259,354,5884,8076,513363
17,Singida,159224,130384,48248,16935,39662,15767,7301,9364,645,...,464,350,224,36,4,169,2548,7673,19282,481794
18,Shinyanga,415972,172045,81310,33417,65534,14036,10818,20233,1898,...,1441,5223,39,88,10,125,128,7667,12435,916946
19,Tabora,278184,69464,42911,18874,32533,11400,3692,15339,1238,...,0,1672,0,0,2,19,111,5822,19252,524208
20,Tanga,453194,219216,67456,45473,121480,26090,20284,16507,3911,...,83,14972,0,58,147,5668,23003,91396,249414,1455493

In [22]:
def tran_mathscrore(x):
    if x=='Rukwa':
        return 1
    if x=='Tabora':
        return 2
df['Trans_MathScore']=df['MathScore'].apply(tran_mathscore)
df

KeyError: 'MathScore'